version: '3'
services:

  machtverlust:
    build:
        dockerfile: Dockerfile
        context: .
    image: machtverlust:latest
    environment:
      VIRTUAL_HOST: ".machtverlust.de"
    #   LETSENCRYPT_HOST: "*.machtverlust.de"
    #   LETSENCRYPT_EMAIL: andy@zieglercloud.de
    restart: always
    network_mode: bridge
